name: mindspice
description: "A Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  path_provider: ^2.0.14
  uuid: ^3.0.7
  csv: ^5.0.1
  file_picker: ^10.3.3
  intl: ^0.18.1
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

# --- APP ICON CONFIGURATION ---
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
